# Two jobs will run : One after another
# Keyword used : uses: another_job_name || [another_jobs1,another_jobs2]

name: Multiple jobs - runs one after another
on: pull_request
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline scripts
        run: |
          npm -v
          node -v

  run-windows-commands:
    runs-on: windows-latest
    needs: run-shell-commands
    steps:
      - name: Print Directory powershell
        run: Get-Location