# Output from actions
name: Output action
on: push
jobs:
  output_actions:
    runs-on: ubuntu-latest
    steps:
      - name: JS output action
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: Ayush

      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time}}"
