# Two jobs will run : One after another

name: Multiple jobs - runs one after another
on: push
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline scripts
        run: |
          npm -v
          node -v

  run-windows-commands:
    runs-on: windows-latest
    steps:
      - name: Print Directory powershell
        needs: ["run-shell-commands"]
        run: Get-Location