name: Show files of workflows dir
on: pull_request
jobs:
  show-files:
    runs-on: ubuntu-latest
    steps:
      - name: Show current files
        run: |
          pwd
          ls -a

      - name: Clone the repo
        uses: actions/checkout@v2

      - name: Show Files now
        run: |
          pwd
          ls -a

      - name: Go to test folder
        run: |
          cd test
          pwd
          ls -a

      - name: Create another folder and create a file
        run: |
          mkdir test2
          touch tes2.html

      - name: Show files
        run: |
          pwd ls -a

      - name: Create new folder
        run: |
          cd ..
          pwd
          mkdir hello

      - name: Show files
        run: |
          pwd
          ls -a