name: Show files of workflows dir
on: push
jobs:
  show-files:
    runs-on: ubuntu-latest
    steps:
      - name: Show current files
        run: |
          pwd
          ls -a

      - name: Clone the repo
        uses: actions/checkout@v2

      - name: Show Files now
        run: |
          pwd
          ls -a

      - name: Go to workflow dir
        run: cd .github/workflows

      - name: Show files
        run: |
          pwd ls -a

      - name: Create new folder
        run: mkdir work2

      - name: Show files
        run: |
          pwd
          ls -a