name: Container workflow
on: push
jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine3.16
    steps:
      - name: Log node version
        run: node -v
      - name: Log information about container
        run: cat /etc/os-release